"""
Vision Protocol Message Info 상수들을 정의하는 모듈
message_api.h의 MSGs enum에서 추출한 실제 값들
"""

# Vision Protocol 메시지 이벤트 ID 상수들 (message_api.h에서 추출)
VISION_MSG_EVENT_WAKEUP = 1
VISION_MSG_REQUEST_VERSION = 2
VISION_MSG_RESPONSE_VERSION = 3

# Stream 관련
VISION_MSG_REQUEST_STREAMINFO = 4
VISION_MSG_RESPONSE_STREAMINFO = 5
VISION_MSG_EVENT_STREAMINFO = 6

# NPU 관련
VISION_MSG_REQUEST_NPU_INFERENCE_TIME = 7
VISION_MSG_RESPONSE_NPU_INFERENCE_TIME = 8
VISION_MSG_EVENT_NPU_INFERENCE_TIME = 9

VISION_MSG_REQUEST_NPU_UTILIZATION = 10
VISION_MSG_RESPONSE_NPU_UTILIZATION = 11
VISION_MSG_EVENT_NPU_UTILIZATION = 12

VISION_MSG_REQUEST_NPU_INFERENCE_OD_BOUNDINGBOX = 13
VISION_MSG_RESPONSE_NPU_INFERENCE_OD_BOUNDINGBOX = 14
VISION_MSG_EVENT_NPU_INFERENCE_OD_BOUNDINGBOX = 15

# 성능 모니터링 관련 (VisionProtocol에서 실제 사용)
VISION_MSG_EVENT_CPU_UTILIZATION = 27
VISION_MSG_EVENT_SDK_MEM_USAGE = 30
VISION_MSG_EVENT_SDK_VIDEO_FPS = 33
VISION_MSG_EVENT_SDK_VIDEO_IMAGE_INFO = 36

# 스트림 제어
VISION_MSG_REQUEST_STREAM_START = 37
VISION_MSG_RESPONSE_STREAM_START = 38
VISION_MSG_EVENT_STREAM_START = 39

VISION_MSG_REQUEST_STREAM_STOP = 40
VISION_MSG_RESPONSE_STREAM_STOP = 41
VISION_MSG_EVENT_STREAM_STOP = 42

# 결과 데이터 (VisionProtocol에서 실제 사용)
VISION_MSG_EVENT_RESULT_STARTSTOP = 43
VISION_MSG_EVENT_RESULT_DATA_JSON = 44
VISION_MSG_EVENT_RESULT_PERF_JSON = 45
VISION_MSG_EVENT_DEWARP_STATUS = 46
VISION_MSG_EVENT_DEWARP_DATA_MSG = 47

# NPU 드라이버 사용률 (VisionProtocol에서 실제 사용)  
VISION_MSG_EVENT_NPU_INFERENCE_DMS_RESULT = 48
VISION_MSG_EVENT_NPU_DRIVER_USAGE = 49

