## NN SDK
Projection:
  width: 1280
  height: 720
  channel: 3
Injection:
  width: 1280
  height: 720
  channel: 3
DetectTypes: [
    NPU0, NPU1
  ]

## Falcon Project
# Projection:
#   width: 1920
#   height: 1080
#   channel: 3
# Injection:
#   width: 1920
#   height: 1280
#   channel: 3
# DetectTypes: [
#     OD, TSR, HBA, LD
#   ]
# Features:
#   Performance: true
#   dewarp: true
